In [ ]:
import numpy as np

# Problem 1: Recap of Today’s Notes
# Exercise: Write the form of the covariance matrix for a 3-variable system. What is the dimension of the covariance matrix?
# 3-variables: X, Y, Z
three_var_cov_mat = [
    ["Cov(X,X)", "Cov(X,Y)", "Cov(X,Z)"],
    ["Cov(Y,X)", "Cov(Y,Y)", "Cov(Y,Z)"],
    ["Cov(Z,X)", "Cov(Z,Y)", "Cov(Z,Z)"],
    ]

"""
Exercise: Read through the numpy documentation for the cov function. Implement your own covariance function (python suggested) based on these notes.
Then, apply your function to the two Examples on the documentation page. Compare your output with np.cov. Do you get the same answers?
"""
def my_cov(vectors):
    vec_1 = vectors[0]
    vec_2 = vectors[1]
    num_elements = len(vec_1)
    d_1 = 1 / (num_elements - 1) * sum([(num - np.mean(vec_1)) * (num - np.mean(vec_1)) for num in vec_1])
    d_2 = 1 / (num_elements - 1) * sum([(num - np.mean(vec_2)) * (num - np.mean(vec_2)) for num in vec_2])
    off_d = 1 / (num_elements - 1) * sum([(vec_1[idx] - np.mean(vec_1)) * (vec_2[idx] - np.mean(vec_2)) for idx in range(num_elements)])
    return [
        [d_1, off_d],
        [off_d, d_2],
    ]

print("----- my_cov output -----")
x = np.array([[0, 2], [1, 1], [2, 0]]).T
print(my_cov(x))

x = [-2.1, -1,  4.3]
y = [3,  1.1,  0.12]
X = np.stack((x, y), axis=0)
print(my_cov(X))

"""
Exercise: The numbers provided in the covariance matrix are “machine readable” but not always intuitive for human interpretation.
A correlation coefficient matrix provides a normalized measurement, with values always between -1 and 1, sometimes useful for interpretation.
Read through the numpy documentation for the corrcoef function and implement your own version on the problem you just completed.
"""
def my_corrcoef(vectors):
    cov = my_cov(vectors)
    num_elements = len(cov)

    def get_r(row, col, cov):
        return cov[row][col] / np.sqrt(cov[row][row] * cov[col][col])

    corrcoef_mat = np.zeros((num_elements, num_elements))

    for i in range(num_elements):
        for j in range(num_elements):
            corrcoef_mat[i][j] = get_r(i, j, cov)

    return corrcoef_mat

print("----- my_corrcoef output -----")
x = np.array([[0, 2], [1, 1], [2, 0]]).T
print(my_corrcoef(x))

x = [-2.1, -1,  4.3]
y = [3,  1.1,  0.12]
X = np.stack((x, y), axis=0)
print(my_corrcoef(X))

----- my_cov output -----
[[1.0, -1.0], [-1.0, 1.0]]
[[11.709999999999999, -4.2860000000000005], [-4.2860000000000005, 2.1441333333333334]]
----- my_corrcoef output -----
[[ 1. -1.]
 [-1.  1.]]
[[ 1.         -0.85535781]
 [-0.85535781  1.        ]]
[[ 1.         -0.85535781]
 [-0.85535781  1.        ]]
